### ISSUE TITLE
what is the $_GET['code']

### ISSUE THREAD

**Issue by zachary** [neilcrookes/oauth2-ebay#2]
what is the $_GET['code'] from ?

thanks

**Comment by neilcrookes** [comment]
@zachary check out the usage instructions on the main [league/oauth2-client](https://github.com/thephpleague/oauth2-client) repo. It's in a query string param after the user grants your app access to their eBay account.

In order to get access to their eBay account, you redirect them to a URL on eBay which you get by calling `$provider->getAuthorizationUrl()`.

What's in the readme in this repo must be read in conjunction with the instructions in the [league/oauth2-client](https://github.com/thephpleague/oauth2-client) repo.
